/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Sake Hack Backend API
 * Sake Hack Backend API

 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from "../axios/client";
export interface APIError {
  /** エラーコード */
  code: string;
  /** エラーメッセージ */
  message: string;
}

/**
 * レスポンスデータ
 * @nullable
 */
export type ErrorResponseData = { [key: string]: unknown } | null;

export interface ErrorResponse {
  /**
   * レスポンスデータ
   * @nullable
   */
  data?: ErrorResponseData;
  /** エラー情報の配列 */
  errors?: APIError[];
}

export interface PaginationMeta {
  /** 総件数 */
  total: number;
  /** 現在のページ番号 */
  page: number;
  /** 1ページあたりの件数 */
  per_page: number;
  /** 総ページ数 */
  total_pages: number;
}

export interface SakeType {
  /** 酒の種類ID */
  id: number;
  /** 酒の種類の名前 */
  name: string;
}

export interface Brewery {
  /** 酒造ID */
  id: number;
  /** 酒造名 */
  name: string;
  /** 所在国 */
  origin_country: string;
  /**
   * 所在地域
   * @nullable
   */
  origin_region?: string | null;
  /**
   * 緯度
   * @nullable
   */
  latitude?: number | null;
  /**
   * 経度
   * @nullable
   */
  longitude?: number | null;
}

export interface DrinkStyle {
  /** 飲み方ID */
  id: number;
  /** 飲み方の名前 */
  name: string;
  /**
   * 詳細説明
   * @nullable
   */
  description?: string | null;
}

export interface Sake {
  /** 酒ID */
  id: number;
  type: SakeType;
  brewery: Brewery;
  /** 酒名 */
  name: string;
  /** アルコール度数(%) */
  abv: number;
  /** 味の特徴 */
  taste_notes: string;
  /**
   * 感想
   * @nullable
   */
  memo?: string | null;
  /** おすすめの飲み方 */
  drink_styles: DrinkStyle[];
  /** 作成日時 */
  created_at: string;
  /** 更新日時 */
  updated_at: string;
}

export interface SakeListMeta {
  /** 総件数 */
  total: number;
  /** スキップした件数 */
  offset: number;
  /** 取得した件数 */
  limit: number;
}

export interface ListSakesResponse {
  /** 酒のリスト */
  data?: Sake[];
  meta?: SakeListMeta;
  errors?: APIError[];
}

/**
 * バリデーションエラー
 */
export type BadRequestResponse = ErrorResponse;

/**
 * 認証失敗
 */
export type UnauthorizedResponse = ErrorResponse;

/**
 * 権限エラー
 */
export type ForbiddenResponse = ErrorResponse;

/**
 * リソースが見つからない
 */
export type NotFoundResponse = ErrorResponse;

/**
 * リソースの競合エラー
 */
export type ConflictResponse = ErrorResponse;

/**
 * サーバー内部エラー
 */
export type InternalServerErrorResponse = ErrorResponse;

export type ListSakesParams = {
  /**
   * スキップする件数
   * @minimum 0
   */
  offset?: number;
  /**
   * 取得する件数
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * 酒の種類IDでフィルタ
   * @minimum 1
   */
  type_id?: number;
  /**
   * 酒造IDでフィルタ
   * @minimum 1
   */
  brewery_id?: number;
};

export const getSakeHackBackendAPI = () => {
  /**
   * 酒の一覧をページネーション付きで取得します
   * @summary 酒一覧取得
   */
  const listSakes = (params?: ListSakesParams) => {
    return customInstance<ListSakesResponse>({
      url: `/sakes`,
      method: "GET",
      params,
    });
  };

  return { listSakes };
};
export type ListSakesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSakeHackBackendAPI>["listSakes"]>>
>;
